### ISSUE TITLE
bug in error exception handling

### ISSUE THREAD

**Issue by FlorianLudwig** [joshmarshall/tornadorpc#1]
File "../lib/tornadorpc/base.py", line 157, in traceback
    err_title += ' - (PARAMS: %s)' % params
TypeError: not all arguments converted during string formatting

Params is a list.

changing the line to:
err_title += ' - (PARAMS: %s)' % repr(params)

solves the problem.

Thanks

**Comment by joshmarshall** [comment]
Thanks for pointing this out!

I've implemented the change and pushed it -- let me know if it solves the problem for you so we can close the issue.

Thanks again!

**Comment by FlorianLudwig** [comment]
Thanks for the fix and the cleanup. Works for me.

FYI the "types" module import is duplicated.
